Repository Sparta-mosaic/msa-mosaic, pull requests merged in 2024-12, with the labels that each got.

#6 [#2] feat: 허브 생성
  hub-service/build.gradle
  hub-service/http/hub.http
  hub-service/src/main/java/org/mosaic/hub/HubServiceApplication.java
  hub-service/src/main/java/org/mosaic/hub/application/dto/CreateHubRequest.java
  hub-service/src/main/java/org/mosaic/hub/application/dto/CreateHubResponse.java
  hub-service/src/main/java/org/mosaic/hub/application/service/HubCommandService.java
  hub-service/src/main/java/org/mosaic/hub/domain/model/Hub.java
  hub-service/src/main/java/org/mosaic/hub/domain/repository/HubRepository.java
  hub-service/src/main/java/org/mosaic/hub/domain/vo/Coordinates.java
  hub-service/src/main/java/org/mosaic/hub/libs/config/AuditingConfig.java
  hub-service/src/main/java/org/mosaic/hub/libs/constant/HttpHeaderConstants.java
  hub-service/src/main/java/org/mosaic/hub/libs/entity/BaseEntity.java
  hub-service/src/main/java/org/mosaic/hub/libs/exception/CustomException.java
  hub-service/src/main/java/org/mosaic/hub/libs/exception/GlobalExceptionHandler.java
  hub-service/src/main/java/org/mosaic/hub/libs/util/ApiResponseUtils.java
  hub-service/src/main/java/org/mosaic/hub/presentation/controller/AdminHubController.java
  hub-service/src/main/resources/application-datasource.yml
  hub-service/src/main/resources/application.properties
  hub-service/src/main/resources/application.yml
  hub-service/src/main/resources/data.sql
  hub-service/src/test/java/org/mosaic/hub/application/service/HubCommandServiceTest.java
  hub-service/src/test/java/org/mosaic/hub/presentation/controller/AdminHubControllerTest.java
  hub-service/src/test/java/org/mosaic/hub_service/HubServiceApplicationTests.java
Labels: enhancement

#11 [#10] refactor: 허브 구조 수정
  hub-service/build.gradle
  hub-service/src/main/java/org/mosaic/hub/application/dtos/CreateHubResponse.java
  hub-service/src/main/java/org/mosaic/hub/application/dtos/CreateHubServiceRequest.java
  hub-service/src/main/java/org/mosaic/hub/application/dtos/HubPageResponse.java
  hub-service/src/main/java/org/mosaic/hub/application/dtos/HubResponse.java
  hub-service/src/main/java/org/mosaic/hub/application/dtos/UpdateHubResponse.java
  hub-service/src/main/java/org/mosaic/hub/application/dtos/UpdateHubServiceRequest.java
  hub-service/src/main/java/org/mosaic/hub/application/service/HubCommandService.java
  hub-service/src/main/java/org/mosaic/hub/application/service/HubQueryService.java
  hub-service/src/main/java/org/mosaic/hub/presentation/controller/AdminHubController.java
  hub-service/src/main/java/org/mosaic/hub/presentation/controller/HubController.java
  hub-service/src/main/java/org/mosaic/hub/presentation/dtos/CreateHubRequest.java
  hub-service/src/main/java/org/mosaic/hub/presentation/dtos/UpdateHubRequest.java
  hub-service/src/test/java/org/mosaic/hub/application/service/HubCommandServiceTest.java
  hub-service/src/test/java/org/mosaic/hub/application/service/HubQueryServiceTest.java
  hub-service/src/test/java/org/mosaic/hub/presentation/controller/AdminHubControllerTest.java
Labels: refactor

#20 [#1] fix: service, controller 분리 및 일부 리팩토링
  auth-service/build.gradle
  auth-service/src/main/java/org/mosaic/auth/company/application/service/CompanyCommandService.java
  auth-service/src/main/java/org/mosaic/auth/company/application/service/CompanyQueryService.java
  auth-service/src/main/java/org/mosaic/auth/company/domain/entity/company/Company.java
  auth-service/src/main/java/org/mosaic/auth/company/presentations/controller/CompanyAdminController.java
  auth-service/src/main/java/org/mosaic/auth/company/presentations/controller/CompanyController.java
  auth-service/src/main/java/org/mosaic/auth/company/presentations/dtos/CreateCompanyRequest.java
  auth-service/src/main/java/org/mosaic/auth/company/presentations/dtos/UpdateCompanyHubIdRequest.java
  auth-service/src/main/java/org/mosaic/auth/company/presentations/dtos/UpdateCompanyRequest.java
  auth-service/src/main/java/org/mosaic/auth/libs/config/base/BaseEntity.java
  auth-service/src/main/java/org/mosaic/auth/libs/config/queryDsl/QueryDslConfig.java
  auth-service/src/main/java/org/mosaic/auth/libs/exception/CustomException.java
  auth-service/src/main/java/org/mosaic/auth/libs/exception/ExceptionStatus.java
  auth-service/src/main/java/org/mosaic/auth/libs/exception/GlobalExceptionHandler.java
  auth-service/src/main/java/org/mosaic/auth/libs/util/ApiResponseUtil.java
  auth-service/src/main/java/org/mosaic/auth/libs/util/ApiResponseUtils.java
  auth-service/src/main/java/org/mosaic/auth/user/application/service/UserCommandService.java
  auth-service/src/main/java/org/mosaic/auth/user/application/service/UserQueryService.java
  auth-service/src/main/java/org/mosaic/auth/user/domain/entity/user/User.java
  auth-service/src/main/java/org/mosaic/auth/user/presentations/controller/UserAdminController.java
  auth-service/src/main/java/org/mosaic/auth/user/presentations/controller/UserController.java
  auth-service/src/main/resources/CompanyHTTPRequest.http
  auth-service/src/main/resources/UserHTTPRequest.http
  auth-service/src/main/resources/application.yml
  auth-service/src/main/resources/data.sql
  auth-service/src/main/resources/schema.sql
Labels: fix

#23 [#22] fix: 중복된 파일로 프로젝트 생성 오류 발생 문제 해결
  auth-service/src/main/java/org/mosaic/auth/company/application/service/CompanyCommandService.java
  auth-service/src/main/java/org/mosaic/auth/company/application/service/CompanyService.java
  auth-service/src/main/java/org/mosaic/auth/company/domain/entity/company/Company.java
  auth-service/src/main/java/org/mosaic/auth/company/presentations/CompanyController.java
  auth-service/src/main/java/org/mosaic/auth/company/presentations/controller/CompanyController.java
  auth-service/src/main/java/org/mosaic/auth/config/base/BaseEntity.java
  auth-service/src/main/java/org/mosaic/auth/config/queryDsl/QueryDslConfig.java
  auth-service/src/main/java/org/mosaic/auth/libs/ApiResponseUtil.java
  auth-service/src/main/java/org/mosaic/auth/libs/util/ApiResponseUtils.java
  auth-service/src/main/java/org/mosaic/auth/user/application/service/UserService.java
  auth-service/src/main/java/org/mosaic/auth/user/domain/entity/user/User.java
  auth-service/src/main/java/org/mosaic/auth/user/presentations/UserController.java
  auth-service/src/main/java/org/mosaic/auth/user/presentations/dto/CreateUserRequest.java
  auth-service/src/main/resources/schema.sql
  auth-service/src/main/resources/user_company_dummy.sql
  auth-service/src/test/java/org/mosaic/auth/UserTest.http
Labels: fix

#25 [#17] feat: server, gateway routing path 설정 완료
  auth-service/build.gradle
  auth-service/src/main/java/org/mosaic/auth/company/application/dtos/CompanyPage.java
  auth-service/src/main/java/org/mosaic/auth/company/application/dtos/CompanyPageResponse.java
  auth-service/src/main/java/org/mosaic/auth/company/application/service/CompanyQueryService.java
  auth-service/src/main/java/org/mosaic/auth/company/presentations/controller/CompanyController.java
  auth-service/src/main/resources/CompanyHTTPRequest.http
  gateway/build.gradle
  gateway/src/main/resources/application.properties
  gateway/src/main/resources/application.yml
  server/build.gradle
  server/src/main/resources/application.properties
  server/src/main/resources/application.yml
Labels: enhancement

#28 fix#27: init data 실패 수정하였습니다
  auth-service/src/main/resources/application.yml
  auth-service/src/main/resources/data.sql
  auth-service/src/main/resources/schema.sql
  server/src/main/java/org/mosaic/server/ServerApplication.java
Labels: fix

#29 [#15] feat: 상품 생성 기능
  product-service/build.gradle
  product-service/src/main/java/org/mosaic/product_service/application/dtos/CreateProductDto.java
  product-service/src/main/java/org/mosaic/product_service/application/dtos/CreateProductResponse.java
  product-service/src/main/java/org/mosaic/product_service/application/mapper/ProductMapper.java
  product-service/src/main/java/org/mosaic/product_service/application/service/ProductMethodService.java
  product-service/src/main/java/org/mosaic/product_service/domain/entity/Product.java
  product-service/src/main/java/org/mosaic/product_service/domain/entity/ProductStockHistory.java
  product-service/src/main/java/org/mosaic/product_service/domain/entity/enums/StockType.java
  product-service/src/main/java/org/mosaic/product_service/domain/repository/ProductRepository.java
  product-service/src/main/java/org/mosaic/product_service/infrastructure/jpa/ProductRepositoryImpl.java
  product-service/src/main/java/org/mosaic/product_service/libs/common/config/JpaAuditConfig.java
  product-service/src/main/java/org/mosaic/product_service/libs/common/constant/HttpHeaderConstants.java
  product-service/src/main/java/org/mosaic/product_service/libs/common/entity/BaseEntity.java
  product-service/src/main/java/org/mosaic/product_service/libs/exception/AuthException.java
  product-service/src/main/java/org/mosaic/product_service/libs/exception/GlobalExceptionHandler.java
  product-service/src/main/java/org/mosaic/product_service/libs/util/ApiResponseUtils.java
  product-service/src/main/java/org/mosaic/product_service/libs/util/MosaicResponse.java
  product-service/src/main/java/org/mosaic/product_service/presentaion/controller/AdminProductController.java
  product-service/src/main/java/org/mosaic/product_service/presentaion/dtos/CreateProductRequest.java
  product-service/src/main/resources/application.properties
  product-service/src/main/resources/application.yaml
  product-service/src/main/resources/data.sql
  product-service/src/main/resources/http/product.http
  product-service/src/main/resources/schema.sql
  product-service/src/test/java/org/mosaic/product_service/presentaion/controller/AdminProductControllerTest.java
Labels: enhancement

#34 [#32] feat: 상품 수정 기능
  product-service/src/main/java/org/mosaic/product_service/application/dtos/UpdateProductDto.java
  product-service/src/main/java/org/mosaic/product_service/application/dtos/UpdateProductResponse.java
  product-service/src/main/java/org/mosaic/product_service/application/mapper/ProductMapper.java
  product-service/src/main/java/org/mosaic/product_service/application/service/ProductCommandService.java
  product-service/src/main/java/org/mosaic/product_service/domain/entity/Product.java
  product-service/src/main/java/org/mosaic/product_service/domain/entity/ProductStockHistory.java
  product-service/src/main/java/org/mosaic/product_service/presentaion/controller/AdminProductController.java
  product-service/src/main/java/org/mosaic/product_service/presentaion/dtos/UpdateProductRequest.java
  product-service/src/main/resources/http/product.http
  product-service/src/test/java/org/mosaic/product_service/presentaion/controller/AdminProductControllerTest.java
Labels: enhancement

#41 [#12] feat: 허브 이동 정보 생성
  hub-service/src/main/java/org/mosaic/hub/application/dtos/CreateHubTransferResponse.java
  hub-service/src/main/java/org/mosaic/hub/application/dtos/CreateHubTransferServiceRequest.java
  hub-service/src/main/java/org/mosaic/hub/application/dtos/HubTransferInfo.java
  hub-service/src/main/java/org/mosaic/hub/application/dtos/HubTransferResponse.java
  hub-service/src/main/java/org/mosaic/hub/application/service/HubCommandService.java
  hub-service/src/main/java/org/mosaic/hub/domain/model/Hub.java
  hub-service/src/main/java/org/mosaic/hub/domain/model/HubTransfer.java
  hub-service/src/main/java/org/mosaic/hub/presentation/controller/AdminHubController.java
  hub-service/src/main/java/org/mosaic/hub/presentation/dtos/CreateHubTransferRequest.java
  hub-service/src/main/resources/application-datasource.yml
  hub-service/src/main/resources/data.sql
  hub-service/src/main/resources/http/hub-transfer.http
  hub-service/src/main/resources/http/hub.http
  hub-service/src/main/resources/schema.sql
  hub-service/src/test/java/org/mosaic/hub/application/service/HubCommandServiceTest.java
  hub-service/src/test/java/org/mosaic/hub/application/service/HubQueryServiceTest.java
  hub-service/src/test/java/org/mosaic/hub/presentation/controller/AdminHubControllerTest.java
Labels: enhancement

#42 [#12] feat: 허브 이동 정보 생성
  hub-service/src/main/java/org/mosaic/hub/domain/model/HubTransfer.java
  hub-service/src/main/resources/data.sql
  hub-service/src/main/resources/schema.sql
Labels: enhancement

#49 [#39] 주문 생성시 상품 재고 차감 후 주문 상태 변경
  order-service/build.gradle
  order-service/src/main/java/org/mosaic/order_service/application/dtos/OrderResponse.java
  order-service/src/main/java/org/mosaic/order_service/application/dtos/ProductDeductDto.java
  order-service/src/main/java/org/mosaic/order_service/application/service/OrderCommandService.java
  order-service/src/main/java/org/mosaic/order_service/application/service/OrderMessageService.java
  order-service/src/main/java/org/mosaic/order_service/application/service/OrderQueryService.java
  order-service/src/main/java/org/mosaic/order_service/domain/entity/Order.java
  order-service/src/main/java/org/mosaic/order_service/domain/repository/OrderRepository.java
  order-service/src/main/java/org/mosaic/order_service/infrastructure/message/ProductDeductProducer.java
  order-service/src/main/java/org/mosaic/order_service/infrastructure/message/ProductDeductResultConsumer.java
  order-service/src/main/java/org/mosaic/order_service/libs/common/config/JpaAuditConfig.java
  order-service/src/main/java/org/mosaic/order_service/libs/common/config/KafkaConfig.java
  order-service/src/main/java/org/mosaic/order_service/libs/exception/GlobalExceptionHandler.java
  order-service/src/main/java/org/mosaic/order_service/libs/exception/OrderNotFoundException.java
  order-service/src/main/java/org/mosaic/order_service/presentation/controller/OrderController.java
  order-service/src/main/resources/application.yaml
  order-service/src/main/resources/http/Order.http
  product-service/build.gradle
  product-service/src/main/java/org/mosaic/product_service/application/dtos/ProductDeductDto.java
  product-service/src/main/java/org/mosaic/product_service/application/service/ProductMessageService.java
  product-service/src/main/java/org/mosaic/product_service/domain/entity/Product.java
  product-service/src/main/java/org/mosaic/product_service/domain/entity/ProductStockHistory.java
  product-service/src/main/java/org/mosaic/product_service/infrastructure/jpa/ProductStockHistoryRepository.java
  product-service/src/main/java/org/mosaic/product_service/infrastructure/message/ProductDeductConsumer.java
  product-service/src/main/java/org/mosaic/product_service/libs/common/config/JpaAuditConfig.java
  product-service/src/main/java/org/mosaic/product_service/libs/exception/GlobalExceptionHandler.java
  product-service/src/main/java/org/mosaic/product_service/libs/exception/InsufficientStockException.java
  product-service/src/main/resources/application.yaml
Labels: enhancement

#56 [#46] 허브 경로 조회
  hub-service/src/main/java/org/mosaic/hub/application/dtos/CreateHubTransferResponse.java
  hub-service/src/main/java/org/mosaic/hub/application/dtos/CreateHubTransferServiceRequest.java
  hub-service/src/main/java/org/mosaic/hub/application/dtos/GetHubPathResponse.java
  hub-service/src/main/java/org/mosaic/hub/application/dtos/HubPathResponse.java
  hub-service/src/main/java/org/mosaic/hub/application/dtos/HubResponse.java
  hub-service/src/main/java/org/mosaic/hub/application/dtos/UpdateHubResponse.java
  hub-service/src/main/java/org/mosaic/hub/application/dtos/UpdateHubTransferServiceRequest.java
  hub-service/src/main/java/org/mosaic/hub/application/service/HubCommandService.java
  hub-service/src/main/java/org/mosaic/hub/application/service/HubQueryService.java
  hub-service/src/main/java/org/mosaic/hub/application/service/HubShortPathService.java
  hub-service/src/main/java/org/mosaic/hub/domain/model/Hub.java
  hub-service/src/main/java/org/mosaic/hub/libs/config/CacheConfig.java
  hub-service/src/main/java/org/mosaic/hub/libs/config/ObjectMapperConfig.java
  hub-service/src/main/java/org/mosaic/hub/libs/init/HubPathCacheInitializer.java
  hub-service/src/main/java/org/mosaic/hub/presentation/controller/HubController.java
  hub-service/src/main/resources/application.yml
  hub-service/src/main/resources/data.sql
  hub-service/src/main/resources/http/hub-path.http
  hub-service/src/main/resources/schema.sql
  hub-service/src/test/java/org/mosaic/hub/application/service/HubCommandServiceTest.java
  hub-service/src/test/java/org/mosaic/hub/presentation/controller/HubControllerTest.java
Labels: enhancement

#62 [#5] refactor: 내부용 허브 조회 엔드포인트 추가
  hub-service/src/main/java/org/mosaic/hub/presentation/controller/ClientHubController.java
Labels: refactor

#64 [#55] Feat: ai-service 응답 메시지 생성 및 저장 구현
  ai-service/build.gradle
  ai-service/src/main/java/org/mosaic/ai/AiServiceApplication.java
  ai-service/src/main/java/org/mosaic/ai/application/dtos/ChatResponse.java
  ai-service/src/main/java/org/mosaic/ai/application/service/GeminiService.java
  ai-service/src/main/java/org/mosaic/ai/domain/entity/AIInteractionLog.java
  ai-service/src/main/java/org/mosaic/ai/domain/repository/AIPromptLogRepository.java
  ai-service/src/main/java/org/mosaic/ai/domain/repository/AIPromptTemplateRepository.java
  ai-service/src/main/java/org/mosaic/ai/libs/config/AuditingConfig.java
  ai-service/src/main/java/org/mosaic/ai/libs/config/GeminiRestTemplateConfig.java
  ai-service/src/main/java/org/mosaic/ai/libs/constant/HttpHeaderConstants.java
  ai-service/src/main/java/org/mosaic/ai/libs/entity/BaseEntity.java
  ai-service/src/main/java/org/mosaic/ai/libs/exception/CustomException.java
  ai-service/src/main/java/org/mosaic/ai/libs/exception/ExceptionStatus.java
  ai-service/src/main/java/org/mosaic/ai/libs/exception/GlobalExceptionHandler.java
  ai-service/src/main/java/org/mosaic/ai/libs/util/ApiResponseUtil.java
  ai-service/src/main/java/org/mosaic/ai/presentation/controller/GeminiController.java
  ai-service/src/main/java/org/mosaic/ai/presentation/dtos/ChatRequest.java
  ai-service/src/main/java/org/mosaic/ai/presentation/dtos/RequestPrompt.java
  ai-service/src/main/java/org/mosaic/ai/presentation/dtos/RequestTemplate.java
  ai-service/src/main/resources/application.properties
  ai-service/src/main/resources/application.yml
  ai-service/src/main/resources/http/AItest.http
  ai-service/src/main/resources/schema.sql
  ai-service/src/test/java/org/mosaic/ai/AiServiceApplicationTests.java
  auth-service/src/main/java/org/mosaic/auth/company/application/service/CompanyCommandService.java
Labels: enhancement

#68 [#39] feat: 배송에 필요한 조회(수령업체 주소, 슬랙)
  auth-service/src/main/java/org/mosaic/auth/libs/common/DeliveryClientController.java
  auth-service/src/main/java/org/mosaic/auth/libs/common/DeliveryClientService.java
  auth-service/src/main/java/org/mosaic/auth/libs/common/dtos/CompanyHubDto.java
  auth-service/src/main/java/org/mosaic/auth/libs/common/dtos/CompanyRequest.java
  auth-service/src/main/java/org/mosaic/auth/libs/common/dtos/DeliveryShippingResponse.java
  auth-service/src/main/java/org/mosaic/auth/libs/common/dtos/ShippingInfo.java
  auth-service/src/main/resources/http/CompanyHTTPRequest.http
Labels: enhancement

#69 [#57] feat: 배송 담당자 생성
  auth-service/src/main/java/org/mosaic/auth/application/dtos/CreateDeliveryDriverResponse.java
  auth-service/src/main/java/org/mosaic/auth/application/dtos/CreateDeliveryDriverService.java
  auth-service/src/main/java/org/mosaic/auth/application/service/DeliveryDriverCommandService.java
  auth-service/src/main/java/org/mosaic/auth/domain/model/delivery_driver/DeliveryDriver.java
  auth-service/src/main/java/org/mosaic/auth/domain/model/delivery_driver/DeliveryDriverType.java
  auth-service/src/main/java/org/mosaic/auth/domain/repository/DeliveryDriverRepository.java
  auth-service/src/main/java/org/mosaic/auth/presentation/controller/delivery_driver/DeliveryDriverController.java
  auth-service/src/main/java/org/mosaic/auth/presentation/dtos/CreateDeliveryDriverRequest.java
  auth-service/src/main/resources/data.sql
  auth-service/src/main/resources/http/delivery-driver.http
  auth-service/src/main/resources/schema.sql
Labels: enhancement
